# Generated by Django 2.1.5 on 2019-02-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=12)),
                ('itemId', models.CharField(max_length=15)),
                ('restaurent_id', models.CharField(max_length=15)),
                ('delivery_id', models.CharField(max_length=15)),
                ('payment_id', models.CharField(max_length=15)),
                ('order_date', models.DateField()),
            ],
        ),
    ]
