# Generated by Django 2.1.5 on 2019-02-12 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=12)),
                ('item_id', models.CharField(max_length=15)),
                ('restaurant_id', models.CharField(max_length=15)),
                ('branch_id', models.CharField(max_length=15)),
                ('delivery_id', models.CharField(max_length=15)),
                ('payment_id', models.CharField(max_length=15)),
                ('order_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='order_entity',
        ),
    ]
