# Generated by Django 2.1.5 on 2019-02-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_restaurant_restaurantbranch_restaurantpkg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestaurantPkg',
            new_name='RestaurantMenuEntry',
        ),
    ]
