# Generated by Django 2.1.5 on 2019-02-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190212_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantmenuentry',
            name='restaurant_id',
        ),
        migrations.DeleteModel(
            name='RestaurantMenuEntry',
        ),
    ]
