# Generated by Django 2.1.5 on 2019-02-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190212_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantMenuEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Restaurant')),
            ],
        ),
    ]
